/**
 * RateCard Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/skus.openapi.types.js";
import { schemas } from "../schemas/skus.schemas.js";

/**
 * Entity: RateCardEntity
 * Description: Represents the RateCard domain model.
 * Source: schemas.RateCard
 * Type: Domain Entity (API)
 */
export const RateCardEntitySchema = schemas.RateCard;
export type RateCardEntity = components["schemas"]["RateCard"];
