/**
 * ActivateDistributionContract handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { activateDistributionContract } from "@shelfline/api-server/domains/distributors/handlers";
import type { DistributorsDDDDependencies } from "@shelfline/api-server/domains/distributors";
import { createCreateActivateRequest } from "@shelfline/factories/distributors";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shelfline/tests/shared";
import { DISTRIBUTORS_USE_CASES } from "../__factories__/use-cases.js";

describe("ActivateDistributionContract", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DistributorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DistributorsDDDDependencies>(
      DISTRIBUTORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateActivateRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeActivateDistributionContract, "execute").mockResolvedValue(useCaseResult);

    await activateDistributionContract(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeActivateDistributionContract.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
