/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Breaches Domain Use Cases
 * 
 * List of all use case names for the breaches domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const BREACHES_USE_CASES = [
  "executeCreateFairnessAttestation",
  "executeGetBreach",
  "executeListBreaches",
  "executeListFairnessAttestations",
  "executeRecordBreach",
  "executeRemediateBreach"
] as const;
