/**
 * ComplaintRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplaintRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ComplaintRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ComplaintRepository,
} from "@shelfline/services/complaints";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ComplaintRepositoryDdb } from "./complaint-repository.ddb.js";

/**
 * ComplaintRepositoryAdapter
 *
 * Implements ComplaintRepository port for infrastructure layer.
 */
export class ComplaintRepositoryAdapter implements ComplaintRepository {
  private readonly ddb: ComplaintRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ComplaintRepositoryDdb(this.dynamoClient);
  }

  async listComplaints(input: Parameters<ComplaintRepository['listComplaints']>[0]): Promise<Awaited<ReturnType<ComplaintRepository['listComplaints']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listComplaints(input);
  }

  async openComplaint(input: Parameters<ComplaintRepository['openComplaint']>[0]): Promise<Awaited<ReturnType<ComplaintRepository['openComplaint']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openComplaint(input);
  }

  async getComplaint(input: Parameters<ComplaintRepository['getComplaint']>[0]): Promise<Awaited<ReturnType<ComplaintRepository['getComplaint']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getComplaint(input);
  }
}
