/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./assign-repository.ddb.js";
export * from "./close-repository.ddb.js";
export * from "./complaint-repository.ddb.js";
export * from "./assign-repository.adapter.js";
export * from "./close-repository.adapter.js";
export * from "./complaint-repository.adapter.js";
