/**
 * ReleaseThrottle handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { releaseThrottle } from "@shelfline/api-server/domains/throttles/handlers";
import type { ThrottlesDDDDependencies } from "@shelfline/api-server/domains/throttles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shelfline/tests/shared";
import { THROTTLES_USE_CASES } from "../__factories__/use-cases.js";

describe("ReleaseThrottle", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ThrottlesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ThrottlesDDDDependencies>(
      THROTTLES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeReleaseThrottle, "execute").mockResolvedValue(useCaseResult);

    await releaseThrottle(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeReleaseThrottle.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
