/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Telemetry Domain Use Cases
 * 
 * List of all use case names for the telemetry domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TELEMETRY_USE_CASES = [
  "executeListCacReports",
  "executeListMarginSnapshots"
] as const;
