/**
 * Attestation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestation DTOs
 *
 * DDD: Application DTOs for Attestation use cases.
 */

import type { CreateFairnessAttestationRequestInput, ListFairnessAttestationsParams } from "@shelfline/core/breaches/types";

export type ListFairnessAttestationsInput = ListFairnessAttestationsParams;

export type CreateFairnessAttestationInput = CreateFairnessAttestationRequestInput;

export type ListFairnessAttestationsOutput = {};

export type CreateFairnessAttestationOutput = {};
