/**
 * Routes for Origination
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getOrigination, listOriginations, submitOrigination } from "../handlers/origination.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function originationRoutes(fastify: FastifyInstance) {
  // GET /v1/originations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/originations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOriginationsDependenciesForRequest();
        await listOriginations(request, reply, deps);
      });
    }
  );


  // POST /v1/originations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/originations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOriginationsDependenciesForRequest();
        await submitOrigination(request, reply, deps);
      });
    }
  );


  // GET /v1/originations/{applicationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/originations/:applicationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOriginationsDependenciesForRequest();
        await getOrigination(request, reply, deps);
      });
    }
  );


}
