/**
 * ListDistributors handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDistributors } from "@shelfline/api-server/domains/distributors/handlers";
import type { DistributorsDDDDependencies } from "@shelfline/api-server/domains/distributors";
import { createDistributor as createDistributorEntity } from "@shelfline/factories/distributors";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shelfline/tests/shared";
import { DISTRIBUTORS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDistributors", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DistributorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DistributorsDDDDependencies>(
      DISTRIBUTORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDistributorEntity({ orgId }),
      createDistributorEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDistributors, "execute").mockResolvedValue(useCaseResult);

    await listDistributors(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDistributors.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
