/**
 * Throttles DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Throttles Domain Module - Composition root
 *
 * DDD: Composition root for throttles domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CapRepositoryAdapter,
  EventRepositoryAdapter,
  ForceRepositoryAdapter,
  ReleaseRepositoryAdapter,
} from "@shelfline/adapters/throttles";
import { getIdGeneratorService } from "@shelfline/adapters";
import type { AdapterDynamoDBClient } from "@shelfline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListLiquidityCaps,
  ExecuteListThrottleEvents,
  ExecuteUpsertLiquidityCap,
} from "@shelfline/services/throttles/usecases";
// Ports (interfaces)
import type {
  CapRepository,
  EventRepository,
  ForceRepository,
  ReleaseRepository,
} from "@shelfline/services/throttles/ports";

export interface ThrottlesDomainModule {
  repos: {
    caps: CapRepository;
    events: EventRepository;
    forces: ForceRepository;
    releases: ReleaseRepository;
  };
  useCases: {
    caps: {
      get: ExecuteUpsertLiquidityCap;
      list: ExecuteListLiquidityCaps;
    };
    events: {
      list: ExecuteListThrottleEvents;
    };
  };
}

export function buildThrottlesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ThrottlesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      caps?: CapRepository;
      events?: EventRepository;
      forces?: ForceRepository;
      releases?: ReleaseRepository;
    } = {};

    obj.caps = new CapRepositoryAdapter(dynamoClient);
    obj.events = new EventRepositoryAdapter(dynamoClient);
    obj.forces = new ForceRepositoryAdapter(dynamoClient);
    obj.releases = new ReleaseRepositoryAdapter(dynamoClient);
    return {
      caps: obj.caps!,
      events: obj.events!,
      forces: obj.forces!,
      releases: obj.releases!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    caps: {
      get: new ExecuteUpsertLiquidityCap(executionContext, idGenerator, repos.caps),
      list: new ExecuteListLiquidityCaps(executionContext, idGenerator, repos.caps),
    },
    events: {
      list: new ExecuteListThrottleEvents(executionContext, idGenerator, repos.events),
    },
  };
  return { repos, useCases: useCases as ThrottlesDomainModule["useCases"] };
}
