/**
 * Handlers for Margin
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TelemetryDomainModule } from "../dependencies/telemetry-ddd.dependencies.js";
import type { ListMarginSnapshotsInput } from "@shelfline/services/telemetry";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/telemetry/margin
 * Operation: listMarginSnapshots
 */
export async function listMarginSnapshots(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], distributorId?: string | string[], skuId?: string | string[], period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TelemetryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListMarginSnapshotsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.margins.list.execute(input);
  return reply.code(200).send(result);
}


