/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Complaints Domain Use Cases
 * 
 * List of all use case names for the complaints domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const COMPLAINTS_USE_CASES = [
  "executeAssignComplaint",
  "executeCloseComplaint",
  "executeGetComplaint",
  "executeListComplaints",
  "executeOpenComplaint"
] as const;
