/**
 * DecisionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionRepository Port
 *
 * DDD: Application port for decisionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DecideOriginationInput, DecideOriginationOutput } from "../dto/decision.dto.js";
export interface DecisionRepository {
  decideOrigination(input: DecideOriginationInput): Promise<DecideOriginationOutput>;
}

export type { DecideOriginationInput, DecideOriginationOutput } from "../dto/decision.dto.js";
