/**
 * ExposureSignalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExposureSignalRepository Port
 *
 * DDD: Application port for exposuresignalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestExposureSignalInput, IngestExposureSignalOutput } from "../dto/exposure-signal.dto.js";
export interface ExposureSignalRepository {
  ingestExposureSignal(input: IngestExposureSignalInput): Promise<IngestExposureSignalOutput>;
}

export type { IngestExposureSignalInput, IngestExposureSignalOutput } from "../dto/exposure-signal.dto.js";
