/**
 * OriginationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OriginationRepository Port
 *
 * DDD: Application port for originationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetOriginationInput, GetOriginationOutput, ListOriginationsInput, ListOriginationsOutput, SubmitOriginationInput, SubmitOriginationOutput } from "../dto/origination.dto.js";
export interface OriginationRepository {
  listOriginations(input: ListOriginationsInput): Promise<ListOriginationsOutput>;
  submitOrigination(input: SubmitOriginationInput): Promise<SubmitOriginationOutput>;
  getOrigination(input: GetOriginationInput): Promise<GetOriginationOutput>;
}

export type { GetOriginationInput, GetOriginationOutput, ListOriginationsInput, ListOriginationsOutput, SubmitOriginationInput, SubmitOriginationOutput } from "../dto/origination.dto.js";
