/**
 * Margin DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Margin DTOs
 *
 * DDD: Application DTOs for Margin use cases.
 */

import type { ListMarginSnapshotsParams } from "@shelfline/core/telemetry/types";

export type ListMarginSnapshotsInput = ListMarginSnapshotsParams;

export type ListMarginSnapshotsOutput = {};
