/**
 * ActivateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ActivateRepository Port
 *
 * DDD: Application port for activaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ActivateDistributionContractInput, ActivateDistributionContractOutput } from "../dto/activate.dto.js";
export interface ActivateRepository {
  activateDistributionContract(input: ActivateDistributionContractInput): Promise<ActivateDistributionContractOutput>;
}

export type { ActivateDistributionContractInput, ActivateDistributionContractOutput } from "../dto/activate.dto.js";
