/**
 * DistributorRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DistributorRepository Port
 *
 * DDD: Application port for distributorrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDistributorInput, GetDistributorOutput, ListDistributorsInput, ListDistributorsOutput, RegisterDistributorInput, RegisterDistributorOutput } from "../dto/distributor.dto.js";
export interface DistributorRepository {
  listDistributors(input: ListDistributorsInput): Promise<ListDistributorsOutput>;
  registerDistributor(input: RegisterDistributorInput): Promise<RegisterDistributorOutput>;
  getDistributor(input: GetDistributorInput): Promise<GetDistributorOutput>;
}

export type { GetDistributorInput, GetDistributorOutput, ListDistributorsInput, ListDistributorsOutput, RegisterDistributorInput, RegisterDistributorOutput } from "../dto/distributor.dto.js";
