/**
 * PauseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PauseRepository Port
 *
 * DDD: Application port for pauserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PauseDistributorInput, PauseDistributorOutput } from "../dto/pause.dto.js";
export interface PauseRepository {
  pauseDistributor(input: PauseDistributorInput): Promise<PauseDistributorOutput>;
}

export type { PauseDistributorInput, PauseDistributorOutput } from "../dto/pause.dto.js";
