/**
 * ListRateCard DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSkuRateCardsParams } from "@shelfline/core/skus";

export function createListRateCardRequest(overrides: Partial<ListSkuRateCardsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
