/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Skus Domain Use Cases
 * 
 * List of all use case names for the skus domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SKUS_USE_CASES = [
  "executeCreateProductSku",
  "executeGetProductSku",
  "executeGetSkuCapitalConstraint",
  "executeListProductSkus",
  "executeListSkuRateCards",
  "executePauseProductSku",
  "executePublishProductSku",
  "executeResumeProductSku",
  "executeRetireProductSku",
  "executeUpdateProductSku",
  "executeUpsertRateCard",
  "executeUpsertSkuCapitalConstraint"
] as const;
