/**
 * ListCap DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListLiquidityCapsParams } from "@shelfline/core/throttles";

export function createListCapRequest(overrides: Partial<ListLiquidityCapsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
