/**
 * Handlers for ExposureSignal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OriginationsDomainModule } from "../dependencies/originations-ddd.dependencies.js";
import type { IngestExposureSignalInput } from "@shelfline/services/originations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/exposure-signals
 * Operation: ingestExposureSignal
 */
export async function ingestExposureSignal(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: OriginationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IngestExposureSignalInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exposureSignals.get.execute(input);
  return reply.code(201).send(result);
}


