/**
 * Contract DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Contract DTOs
 *
 * DDD: Application DTOs for Contract use cases.
 */

import type { AmendDistributionContractParams, AmendDistributionContractRequestInput, CreateDistributionContractParams, CreateDistributionContractRequestInput, GetDistributionContractParams, ListDistributionContractsParams } from "@shelfline/core/distributors/types";

export type ListDistributionContractsInput = ListDistributionContractsParams;

export type CreateDistributionContractInput = CreateDistributionContractParams & CreateDistributionContractRequestInput;

export type GetDistributionContractInput = GetDistributionContractParams;

export type AmendDistributionContractInput = AmendDistributionContractParams & AmendDistributionContractRequestInput;

export type ListDistributionContractsOutput = {};

export type CreateDistributionContractOutput = {};

export type GetDistributionContractOutput = {};

export type AmendDistributionContractOutput = {};
