/**
 * Distributor DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Distributor DTOs
 *
 * DDD: Application DTOs for Distributor use cases.
 */

import type { GetDistributorParams, ListDistributorsParams, RegisterDistributorRequestInput } from "@shelfline/core/distributors/types";

export type ListDistributorsInput = ListDistributorsParams;

export type RegisterDistributorInput = RegisterDistributorRequestInput;

export type GetDistributorInput = GetDistributorParams;

export type ListDistributorsOutput = {};

export type RegisterDistributorOutput = {};

export type GetDistributorOutput = {};
