/**
 * CapitalConstraintRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CapitalConstraintRepository Port
 *
 * DDD: Application port for capitalconstraintrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSkuCapitalConstraintInput, GetSkuCapitalConstraintOutput, UpsertSkuCapitalConstraintInput, UpsertSkuCapitalConstraintOutput } from "../dto/capital-constraint.dto.js";
export interface CapitalConstraintRepository {
  getSkuCapitalConstraint(input: GetSkuCapitalConstraintInput): Promise<GetSkuCapitalConstraintOutput>;
  upsertSkuCapitalConstraint(input: UpsertSkuCapitalConstraintInput): Promise<UpsertSkuCapitalConstraintOutput>;
}

export type { GetSkuCapitalConstraintInput, GetSkuCapitalConstraintOutput, UpsertSkuCapitalConstraintInput, UpsertSkuCapitalConstraintOutput } from "../dto/capital-constraint.dto.js";
