/**
 * PublishPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PublishPublisher Port
 *
 * DDD: Application port for publishpublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishProductSkuInput, PublishProductSkuOutput } from "../dto/publish.dto.js";
export interface PublishPublisher {
  publishProductSku(input: PublishProductSkuInput): Promise<PublishProductSkuOutput>;
}

export type { PublishProductSkuInput, PublishProductSkuOutput } from "../dto/publish.dto.js";
