/**
 * RateCardRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RateCardRepository Port
 *
 * DDD: Application port for ratecardrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListSkuRateCardsInput, ListSkuRateCardsOutput, UpsertRateCardInput, UpsertRateCardOutput } from "../dto/rate-card.dto.js";
export interface RateCardRepository {
  listSkuRateCards(input: ListSkuRateCardsInput): Promise<ListSkuRateCardsOutput>;
  upsertRateCard(input: UpsertRateCardInput): Promise<UpsertRateCardOutput>;
}

export type { ListSkuRateCardsInput, ListSkuRateCardsOutput, UpsertRateCardInput, UpsertRateCardOutput } from "../dto/rate-card.dto.js";
