/**
 * ResumeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResumeRepository Port
 *
 * DDD: Application port for resumerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ResumeProductSkuInput, ResumeProductSkuOutput } from "../dto/resume.dto.js";
export interface ResumeRepository {
  resumeProductSku(input: ResumeProductSkuInput): Promise<ResumeProductSkuOutput>;
}

export type { ResumeProductSkuInput, ResumeProductSkuOutput } from "../dto/resume.dto.js";
