/**
 * RetireRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RetireRepository Port
 *
 * DDD: Application port for retirerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RetireProductSkuInput, RetireProductSkuOutput } from "../dto/retire.dto.js";
export interface RetireRepository {
  retireProductSku(input: RetireProductSkuInput): Promise<RetireProductSkuOutput>;
}

export type { RetireProductSkuInput, RetireProductSkuOutput } from "../dto/retire.dto.js";
