/**
 * GetComplaint DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetComplaintParams } from "@shelfline/core/complaints";

export function createGetComplaintRequest(overrides: Partial<GetComplaintParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
