/**
 * PublishProductSku handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { publishProductSku } from "@shelfline/api-server/domains/skus/handlers";
import type { SkusDDDDependencies } from "@shelfline/api-server/domains/skus";
import { createCreatePublishRequest } from "@shelfline/factories/skus";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shelfline/tests/shared";
import { SKUS_USE_CASES } from "../__factories__/use-cases.js";

describe("PublishProductSku", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SkusDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SkusDDDDependencies>(
      SKUS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreatePublishRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePublishProductSku, "execute").mockResolvedValue(useCaseResult);

    await publishProductSku(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePublishProductSku.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
