apis:
  identity:
    root: src/identity.yaml
  skus:
    root: src/skus.yaml
  distributors:
    root: src/distributors.yaml
  originations:
    root: src/originations.yaml
  throttles:
    root: src/throttles.yaml
  telemetry:
    root: src/telemetry.yaml
  complaints:
    root: src/complaints.yaml
  breaches:
    root: src/breaches.yaml

extends:
  - recommended

rules:
  no-unused-components: off
  operation-4xx-response: warn
  info-license: off
  info-license-url: off
  tag-description: off
  operation-operationId: error
  no-invalid-media-type-examples: off

theme:
  openapi:
    generateCodeSamples:
      languages: []
