/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { capRoutes } from "./cap.routes.js";
export { eventRoutes } from "./event.routes.js";
export { forceRoutes } from "./force.routes.js";
export { releaseRoutes } from "./release.routes.js";
