/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @shelfline/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@shelfline/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@shelfline/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@shelfline/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@shelfline/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@shelfline/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _breaches from "./breaches/index.js";
import * as _complaints from "./complaints/index.js";
import * as _distributors from "./distributors/index.js";
import * as _identity from "./identity/index.js";
import * as _originations from "./originations/index.js";
import * as _skus from "./skus/index.js";
import * as _telemetry from "./telemetry/index.js";
import * as _throttles from "./throttles/index.js";

// Export as namespaces
export const _shared = __shared;
export const breaches = _breaches;
export const complaints = _complaints;
export const distributors = _distributors;
export const identity = _identity;
export const originations = _originations;
export const skus = _skus;
export const telemetry = _telemetry;
export const throttles = _throttles;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@shelfline/core"; activity.types.*
//   - Direct exports: import * from "@shelfline/core/activity/types/index.js"
//   - Direct exports: import * from "@shelfline/core/activity/repositories/index.js"
//   - Direct exports: import * from "@shelfline/core/activity/models/index.js"
//   - Direct exports: import * from "@shelfline/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Breaches Service
export { schemas as BreachesSchemas } from "./breaches/schemas/breaches.schemas.js";

// Complaints Service
export { schemas as ComplaintsSchemas } from "./complaints/schemas/complaints.schemas.js";

// Distributors Service
export { schemas as DistributorsSchemas } from "./distributors/schemas/distributors.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Originations Service
export { schemas as OriginationsSchemas } from "./originations/schemas/originations.schemas.js";

// Skus Service
export { schemas as SkusSchemas } from "./skus/schemas/skus.schemas.js";

// Telemetry Service
export { schemas as TelemetrySchemas } from "./telemetry/schemas/telemetry.schemas.js";

// Throttles Service
export { schemas as ThrottlesSchemas } from "./throttles/schemas/throttles.schemas.js";

