/**
 * Handlers for Breach
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BreachesDomainModule } from "../dependencies/breaches-ddd.dependencies.js";
import type { GetBreachInput, ListBreachesInput, RecordBreachInput } from "@shelfline/services/breaches";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/breaches
 * Operation: listBreaches
 */
export async function listBreaches(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], distributorId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBreachesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.breaches.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/breaches
 * Operation: recordBreach
 */
export async function recordBreach(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BreachesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordBreachInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.breaches.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/breaches/{breachId}
 * Operation: getBreach
 */
export async function getBreach(
  request: FastifyRequest<{ Params: { breachId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetBreachInput = {
    breachId: request.params.breachId,
  };
  const result = await deps.useCases.breaches.get.execute(input);
  return reply.code(200).send(result);
}


