/**
 * Handlers for Remediate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BreachesDomainModule } from "../dependencies/breaches-ddd.dependencies.js";
import type { RemediateBreachInput } from "@shelfline/services/breaches";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/breaches/{breachId}/remediate
 * Operation: remediateBreach
 */
export async function remediateBreach(
  request: FastifyRequest<{ Params: { breachId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RemediateBreachInput = {
    breachId: request.params.breachId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.remediates.get.execute(input);
  return reply.code(200).send(result);
}


