/**
 * SkuRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SkuRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SkuRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SkuRepository,
} from "@shelfline/services/skus";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SkuRepositoryDdb } from "./sku-repository.ddb.js";

/**
 * SkuRepositoryAdapter
 *
 * Implements SkuRepository port for infrastructure layer.
 */
export class SkuRepositoryAdapter implements SkuRepository {
  private readonly ddb: SkuRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SkuRepositoryDdb(this.dynamoClient);
  }

  async listProductSkus(input: Parameters<SkuRepository['listProductSkus']>[0]): Promise<Awaited<ReturnType<SkuRepository['listProductSkus']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listProductSkus(input);
  }

  async createProductSku(input: Parameters<SkuRepository['createProductSku']>[0]): Promise<Awaited<ReturnType<SkuRepository['createProductSku']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createProductSku(input);
  }

  async getProductSku(input: Parameters<SkuRepository['getProductSku']>[0]): Promise<Awaited<ReturnType<SkuRepository['getProductSku']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getProductSku(input);
  }

  async updateProductSku(input: Parameters<SkuRepository['updateProductSku']>[0]): Promise<Awaited<ReturnType<SkuRepository['updateProductSku']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateProductSku(input);
  }
}
