/**
 * CapitalConstraint Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CapitalConstraintEntity } from "@shelfline/core/skus/models/index.js";
import { skusSchemas } from "@shelfline/core/skus";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "sku";

export function createCapitalConstraint(overrides: Partial<CapitalConstraintEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    currency: overrides.currency ?? faker.lorem.word(),
    maxVolume: overrides.maxVolume ?? faker.number.int(),
    skuId: overrides.skuId ?? faker.string.uuid(),
    ...overrides,
  };

  return skusSchemas.CapitalConstraint.parse(raw);
}

export function capitalConstraintBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCapitalConstraint(overrides));
}
