/**
 * ExposureSignal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExposureSignal DTOs
 *
 * DDD: Application DTOs for ExposureSignal use cases.
 */

import type { IngestExposureSignalRequestInput } from "@shelfline/core/originations/types";

export type IngestExposureSignalInput = IngestExposureSignalRequestInput;

export type IngestExposureSignalOutput = {};
