/**
 * Pause DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pause DTOs
 *
 * DDD: Application DTOs for Pause use cases.
 */

import type { PauseProductSkuParams, PauseProductSkuRequestInput } from "@shelfline/core/skus/types";

export type PauseProductSkuInput = PauseProductSkuParams & PauseProductSkuRequestInput;

export type PauseProductSkuOutput = {};
