/**
 * Publish DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Publish DTOs
 *
 * DDD: Application DTOs for Publish use cases.
 */

import type { PublishProductSkuParams } from "@shelfline/core/skus/types";

export type PublishProductSkuInput = PublishProductSkuParams;

export type PublishProductSkuOutput = {};
