/**
 * RateCard DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RateCard DTOs
 *
 * DDD: Application DTOs for RateCard use cases.
 */

import type { ListSkuRateCardsParams, UpsertRateCardParams, UpsertRateCardRequestInput } from "@shelfline/core/skus/types";

export type ListSkuRateCardsInput = ListSkuRateCardsParams;

export type UpsertRateCardInput = UpsertRateCardParams & UpsertRateCardRequestInput;

export type ListSkuRateCardsOutput = {};

export type UpsertRateCardOutput = {};
