/**
 * Resume DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Resume DTOs
 *
 * DDD: Application DTOs for Resume use cases.
 */

import type { ResumeProductSkuParams, ResumeProductSkuRequestInput } from "@shelfline/core/skus/types";

export type ResumeProductSkuInput = ResumeProductSkuParams & ResumeProductSkuRequestInput;

export type ResumeProductSkuOutput = {};
