/**
 * Retire DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Retire DTOs
 *
 * DDD: Application DTOs for Retire use cases.
 */

import type { RetireProductSkuParams } from "@shelfline/core/skus/types";

export type RetireProductSkuInput = RetireProductSkuParams;

export type RetireProductSkuOutput = {};
