/**
 * Sku DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Sku DTOs
 *
 * DDD: Application DTOs for Sku use cases.
 */

import type { CreateProductSkuRequestInput, GetProductSkuParams, ListProductSkusParams, UpdateProductSkuParams, UpdateProductSkuRequestInput } from "@shelfline/core/skus/types";

export type ListProductSkusInput = ListProductSkusParams;

export type CreateProductSkuInput = CreateProductSkuRequestInput;

export type GetProductSkuInput = GetProductSkuParams;

export type UpdateProductSkuInput = UpdateProductSkuParams & UpdateProductSkuRequestInput;

export type ListProductSkusOutput = {};

export type CreateProductSkuOutput = {};

export type GetProductSkuOutput = {};

export type UpdateProductSkuOutput = {};
