/**
 * Handlers for CapitalConstraint
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SkusDomainModule } from "../dependencies/skus-ddd.dependencies.js";
import type { GetSkuCapitalConstraintInput, UpsertSkuCapitalConstraintInput } from "@shelfline/services/skus";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/skus/{skuId}/capital-constraint
 * Operation: getSkuCapitalConstraint
 */
export async function getSkuCapitalConstraint(
  request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SkusDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSkuCapitalConstraintInput = {
    skuId: request.params.skuId,
  };
  const result = await deps.useCases.capitalConstraints.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/skus/{skuId}/capital-constraint
 * Operation: upsertSkuCapitalConstraint
 */
export async function upsertSkuCapitalConstraint(
  request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SkusDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertSkuCapitalConstraintInput = {
    skuId: request.params.skuId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.capitalConstraints.get.execute(input);
  return reply.code(200).send(result);
}


