/**
 * Handlers for Pause
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SkusDomainModule } from "../dependencies/skus-ddd.dependencies.js";
import type { PauseProductSkuInput } from "@shelfline/services/skus";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/skus/{skuId}/pause
 * Operation: pauseProductSku
 */
export async function pauseProductSku(
  request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SkusDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PauseProductSkuInput = {
    skuId: request.params.skuId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.pauses.get.execute(input);
  return reply.code(200).send(result);
}


