/**
 * Handlers for Cap
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ThrottlesDomainModule } from "../dependencies/throttles-ddd.dependencies.js";
import type { ListLiquidityCapsInput, UpsertLiquidityCapInput } from "@shelfline/services/throttles";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/throttles/caps
 * Operation: listLiquidityCaps
 */
export async function listLiquidityCaps(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], skuId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ThrottlesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLiquidityCapsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.caps.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/throttles/caps
 * Operation: upsertLiquidityCap
 */
export async function upsertLiquidityCap(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ThrottlesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertLiquidityCapInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.caps.get.execute(input);
  return reply.code(200).send(result);
}


