/**
 * ExposureSignal Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/originations.openapi.types.js";
import { schemas } from "../schemas/originations.schemas.js";

/**
 * Entity: ExposureSignalEntity
 * Description: Represents the ExposureSignal domain model.
 * Source: schemas.ExposureSignal
 * Type: Domain Entity (API)
 */
export const ExposureSignalEntitySchema = schemas.ExposureSignal;
export type ExposureSignalEntity = components["schemas"]["ExposureSignal"];
