/**
 * Telemetry DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Telemetry Domain Module - Composition root
 *
 * DDD: Composition root for telemetry domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CacRepositoryAdapter,
  MarginRepositoryAdapter,
} from "@shelfline/adapters/telemetry";
import { getIdGeneratorService } from "@shelfline/adapters";
import type { AdapterDynamoDBClient } from "@shelfline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListCacReports,
  ExecuteListMarginSnapshots,
} from "@shelfline/services/telemetry/usecases";
// Ports (interfaces)
import type {
  CacRepository,
  MarginRepository,
} from "@shelfline/services/telemetry/ports";

export interface TelemetryDomainModule {
  repos: {
    cacs: CacRepository;
    margins: MarginRepository;
  };
  useCases: {
    cacs: {
      list: ExecuteListCacReports;
    };
    margins: {
      list: ExecuteListMarginSnapshots;
    };
  };
}

export function buildTelemetryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TelemetryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      cacs?: CacRepository;
      margins?: MarginRepository;
    } = {};

    obj.cacs = new CacRepositoryAdapter(dynamoClient);
    obj.margins = new MarginRepositoryAdapter(dynamoClient);
    return {
      cacs: obj.cacs!,
      margins: obj.margins!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    cacs: {
      list: new ExecuteListCacReports(executionContext, idGenerator, repos.cacs),
    },
    margins: {
      list: new ExecuteListMarginSnapshots(executionContext, idGenerator, repos.margins),
    },
  };
  return { repos, useCases: useCases as TelemetryDomainModule["useCases"] };
}
