/**
 * ActivateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ActivateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ActivateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ActivateRepository,
} from "@shelfline/services/distributors";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ActivateRepositoryDdb } from "./activate-repository.ddb.js";

/**
 * ActivateRepositoryAdapter
 *
 * Implements ActivateRepository port for infrastructure layer.
 */
export class ActivateRepositoryAdapter implements ActivateRepository {
  private readonly ddb: ActivateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ActivateRepositoryDdb(this.dynamoClient);
  }

  async activateDistributionContract(input: Parameters<ActivateRepository['activateDistributionContract']>[0]): Promise<Awaited<ReturnType<ActivateRepository['activateDistributionContract']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.activateDistributionContract(input);
  }
}
