/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./activate-repository.ddb.js";
export * from "./contract-repository.ddb.js";
export * from "./distributor-repository.ddb.js";
export * from "./pause-repository.ddb.js";
export * from "./resume-repository.ddb.js";
export * from "./activate-repository.adapter.js";
export * from "./contract-repository.adapter.js";
export * from "./distributor-repository.adapter.js";
export * from "./pause-repository.adapter.js";
export * from "./resume-repository.adapter.js";
