/**
 * PauseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PauseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PauseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PauseRepository,
} from "@shelfline/services/distributors";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PauseRepositoryDdb } from "./pause-repository.ddb.js";

/**
 * PauseRepositoryAdapter
 *
 * Implements PauseRepository port for infrastructure layer.
 */
export class PauseRepositoryAdapter implements PauseRepository {
  private readonly ddb: PauseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PauseRepositoryDdb(this.dynamoClient);
  }

  async pauseDistributor(input: Parameters<PauseRepository['pauseDistributor']>[0]): Promise<Awaited<ReturnType<PauseRepository['pauseDistributor']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.pauseDistributor(input);
  }
}
