/**
 * Repository interface for CapitalConstraint
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CapitalConstraintEntity
} from "../models/capital-constraint.entity.js";
import type {
  UpsertSkuCapitalConstraintRequestInput
} from "../types/index.js";
/**
 * CapitalConstraintRepository Interface
 */
export interface CapitalConstraintRepository extends UpdateReadRepository<CapitalConstraintEntity, UpsertSkuCapitalConstraintRequestInput, string, Record<string, never>> {

}
