/**
 * Breaches DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Breaches Domain Module - Composition root
 *
 * DDD: Composition root for breaches domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AttestationRepositoryAdapter,
  BreachRepositoryAdapter,
  RemediateRepositoryAdapter,
} from "@shelfline/adapters/breaches";
import { getIdGeneratorService } from "@shelfline/adapters";
import type { AdapterDynamoDBClient } from "@shelfline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateFairnessAttestation,
  ExecuteGetBreach,
  ExecuteListBreaches,
  ExecuteListFairnessAttestations,
  ExecuteRecordBreach,
} from "@shelfline/services/breaches/usecases";
// Ports (interfaces)
import type {
  AttestationRepository,
  BreachRepository,
  RemediateRepository,
} from "@shelfline/services/breaches/ports";

export interface BreachesDomainModule {
  repos: {
    attestations: AttestationRepository;
    breaches: BreachRepository;
    remediates: RemediateRepository;
  };
  useCases: {
    attestations: {
      create: ExecuteCreateFairnessAttestation;
      list: ExecuteListFairnessAttestations;
    };
    breaches: {
      get: ExecuteGetBreach;
      list: ExecuteListBreaches;
    };
  };
}

export function buildBreachesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BreachesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      attestations?: AttestationRepository;
      breaches?: BreachRepository;
      remediates?: RemediateRepository;
    } = {};

    obj.attestations = new AttestationRepositoryAdapter(dynamoClient);
    obj.breaches = new BreachRepositoryAdapter(dynamoClient);
    obj.remediates = new RemediateRepositoryAdapter(dynamoClient);
    return {
      attestations: obj.attestations!,
      breaches: obj.breaches!,
      remediates: obj.remediates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    attestations: {
      create: new ExecuteCreateFairnessAttestation(executionContext, idGenerator, repos.attestations),
      list: new ExecuteListFairnessAttestations(executionContext, idGenerator, repos.attestations),
    },
    breaches: {
      get: new ExecuteGetBreach(executionContext, idGenerator, repos.breaches),
      list: new ExecuteListBreaches(executionContext, idGenerator, repos.breaches),
    },
  };
  return { repos, useCases: useCases as BreachesDomainModule["useCases"] };
}
