/**
 * AmendDistributionContract handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { amendDistributionContract } from "@shelfline/api-server/domains/distributors/handlers";
import type { DistributorsDDDDependencies } from "@shelfline/api-server/domains/distributors";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shelfline/tests/shared";
import { DISTRIBUTORS_USE_CASES } from "../__factories__/use-cases.js";

describe("AmendDistributionContract", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DistributorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DistributorsDDDDependencies>(
      DISTRIBUTORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { contractId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAmendDistributionContract, "execute").mockResolvedValue(useCaseResult);

    await amendDistributionContract(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAmendDistributionContract.execute).toHaveBeenCalledWith(expect.objectContaining({ contractId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
