/**
 * GetDistributionContract handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDistributionContract } from "@shelfline/api-server/domains/distributors/handlers";
import type { DistributorsDDDDependencies } from "@shelfline/api-server/domains/distributors";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shelfline/tests/shared";
import { DISTRIBUTORS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDistributionContract", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DistributorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DistributorsDDDDependencies>(
      DISTRIBUTORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDistributionContract, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { contractId: entity.id };

    await getDistributionContract(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDistributionContract.execute).toHaveBeenCalledWith(expect.objectContaining({ contractId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { contractId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDistributionContract, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDistributionContract(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
