/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./amend-distribution-contract.handler.test.js";
export * from "./create-distribution-contract.handler.test.js";
export * from "./get-distribution-contract.handler.test.js";
export * from "./list-distribution-contracts.handler.test.js";
