/**
 * AssignRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssignRepository Port
 *
 * DDD: Application port for assignrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AssignComplaintInput, AssignComplaintOutput } from "../dto/assign.dto.js";
export interface AssignRepository {
  assignComplaint(input: AssignComplaintInput): Promise<AssignComplaintOutput>;
}

export type { AssignComplaintInput, AssignComplaintOutput } from "../dto/assign.dto.js";
