/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildBreachesDomainModule } from "./breaches/dependencies/breaches-ddd.dependencies.js";
export { buildComplaintsDomainModule } from "./complaints/dependencies/complaints-ddd.dependencies.js";
export { buildDistributorsDomainModule } from "./distributors/dependencies/distributors-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildOriginationsDomainModule } from "./originations/dependencies/originations-ddd.dependencies.js";
export { buildSkusDomainModule } from "./skus/dependencies/skus-ddd.dependencies.js";
export { buildTelemetryDomainModule } from "./telemetry/dependencies/telemetry-ddd.dependencies.js";
export { buildThrottlesDomainModule } from "./throttles/dependencies/throttles-ddd.dependencies.js";

// Export all domain dependency types
export type { BreachesDomainModule } from "./breaches/dependencies/breaches-ddd.dependencies.js";
export type { ComplaintsDomainModule } from "./complaints/dependencies/complaints-ddd.dependencies.js";
export type { DistributorsDomainModule } from "./distributors/dependencies/distributors-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { OriginationsDomainModule } from "./originations/dependencies/originations-ddd.dependencies.js";
export type { SkusDomainModule } from "./skus/dependencies/skus-ddd.dependencies.js";
export type { TelemetryDomainModule } from "./telemetry/dependencies/telemetry-ddd.dependencies.js";
export type { ThrottlesDomainModule } from "./throttles/dependencies/throttles-ddd.dependencies.js";
