/**
 * Handlers for Complaint
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ComplaintsDomainModule } from "../dependencies/complaints-ddd.dependencies.js";
import type { GetComplaintInput, ListComplaintsInput, OpenComplaintInput } from "@shelfline/services/complaints";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/complaints
 * Operation: listComplaints
 */
export async function listComplaints(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], distributorId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ComplaintsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListComplaintsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.complaints.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/complaints
 * Operation: openComplaint
 */
export async function openComplaint(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ComplaintsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenComplaintInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.complaints.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/complaints/{complaintId}
 * Operation: getComplaint
 */
export async function getComplaint(
  request: FastifyRequest<{ Params: { complaintId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ComplaintsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetComplaintInput = {
    complaintId: request.params.complaintId,
  };
  const result = await deps.useCases.complaints.get.execute(input);
  return reply.code(200).send(result);
}


