/**
 * Repository interface for ExposureSignal
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExposureSignalEntity
} from "../models/exposure-signal.entity.js";
import type {
  ExposureSignal
} from "../types/index.js";
/**
 * ExposureSignalRepository Interface
 */
export interface ExposureSignalRepository extends CreateReadRepository<ExposureSignalEntity, ExposureSignal, string, Record<string, never>> {

}
