/**
 * ExecuteGetOrigination - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetOrigination Use Case
 *
 * DDD: Application use case for get Origination.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetOriginationInput, GetOriginationOutput } from "../dto/origination.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { OriginationRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteGetOrigination {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly origination: OriginationRepository
  ) {}

  async execute(input: GetOriginationInput): Promise<GetOriginationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.orgId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).applicationId) {
      throw new ValidationError("applicationId is required");
    }
    const applicationId = (input as any).applicationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.origination.getOrigination({ applicationId: applicationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${applicationId}`);
    }

    return entity as GetOriginationOutput;
  }
}
