/**
 * ExecuteSubmitOrigination - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitOrigination Use Case
 *
 * DDD: Application use case for create Origination.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitOriginationInput, SubmitOriginationOutput } from "../dto/origination.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { OriginationRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanCreate } from "../policies/can-create.policy.js";
export class ExecuteSubmitOrigination {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly origination: OriginationRepository
  ) {}

  async execute(input: SubmitOriginationInput): Promise<SubmitOriginationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.orgId();

    // All field names extracted from OpenAPI spec: amount, applicantRef, distributorId, skuId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.applicantRef) {
      throw new ValidationError("applicantRef is required");
    }
    if (!input.distributorId) {
      throw new ValidationError("distributorId is required");
    }
    if (!input.amount) {
      throw new ValidationError("amount is required");
    }
    if (!input.skuId) {
      throw new ValidationError("skuId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (originations domain)
    const entityId = this.idGenerator.orgId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.origination.submitOrigination({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitOriginationOutput;
  }
}
