/**
 * ExecuteDecideOrigination - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDecideOrigination Use Case
 *
 * DDD: Application use case for get Decision.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DecideOriginationInput, DecideOriginationOutput } from "../dto/decision.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { DecisionRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteDecideOrigination {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decision: DecisionRepository
  ) {}

  async execute(input: DecideOriginationInput): Promise<DecideOriginationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.orgId();

    // All field names extracted from OpenAPI spec: adverseActionCode, decidedBy, outcome
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).applicationId) {
      throw new ValidationError("applicationId is required");
    }
    const applicationId = (input as any).applicationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.decision.decideOrigination({ applicationId: applicationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${applicationId}`);
    }

    return entity as DecideOriginationOutput;
  }
}
