/**
 * ExecuteIngestExposureSignal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestExposureSignal Use Case
 *
 * DDD: Application use case for get ExposureSignal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestExposureSignalInput, IngestExposureSignalOutput } from "../dto/exposure-signal.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { ExposureSignalRepository } from "../ports/index.js";
import { NotFoundError } from "../errors/index.js";

export class ExecuteIngestExposureSignal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exposureSignal: ExposureSignalRepository
  ) {}

  async execute(input: IngestExposureSignalInput): Promise<IngestExposureSignalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.orgId();

    // All field names extracted from OpenAPI spec: applicantRef, source, totalLeverage
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.exposureSignal.ingestExposureSignal({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as IngestExposureSignalOutput;
  }
}
