/**
 * BreachRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BreachRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BreachRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BreachRepository,
} from "@shelfline/services/breaches";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BreachRepositoryDdb } from "./breach-repository.ddb.js";

/**
 * BreachRepositoryAdapter
 *
 * Implements BreachRepository port for infrastructure layer.
 */
export class BreachRepositoryAdapter implements BreachRepository {
  private readonly ddb: BreachRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BreachRepositoryDdb(this.dynamoClient);
  }

  async listBreaches(input: Parameters<BreachRepository['listBreaches']>[0]): Promise<Awaited<ReturnType<BreachRepository['listBreaches']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBreaches(input);
  }

  async recordBreach(input: Parameters<BreachRepository['recordBreach']>[0]): Promise<Awaited<ReturnType<BreachRepository['recordBreach']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordBreach(input);
  }

  async getBreach(input: Parameters<BreachRepository['getBreach']>[0]): Promise<Awaited<ReturnType<BreachRepository['getBreach']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBreach(input);
  }
}
