/**
 * RemediateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RemediateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RemediateRepository,
} from "@shelfline/services/breaches";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RemediateRepositoryDdb } from "./remediate-repository.ddb.js";

/**
 * RemediateRepositoryAdapter
 *
 * Implements RemediateRepository port for infrastructure layer.
 */
export class RemediateRepositoryAdapter implements RemediateRepository {
  private readonly ddb: RemediateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RemediateRepositoryDdb(this.dynamoClient);
  }

  async remediateBreach(input: Parameters<RemediateRepository['remediateBreach']>[0]): Promise<Awaited<ReturnType<RemediateRepository['remediateBreach']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.remediateBreach(input);
  }
}
