/**
 * Handlers for Distributor
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DistributorsDomainModule } from "../dependencies/distributors-ddd.dependencies.js";
import type { GetDistributorInput, ListDistributorsInput, RegisterDistributorInput } from "@shelfline/services/distributors";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/distributors
 * Operation: listDistributors
 */
export async function listDistributors(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DistributorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDistributorsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.distributors.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/distributors
 * Operation: registerDistributor
 */
export async function registerDistributor(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DistributorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterDistributorInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.distributors.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/distributors/{distributorId}
 * Operation: getDistributor
 */
export async function getDistributor(
  request: FastifyRequest<{ Params: { distributorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DistributorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDistributorInput = {
    distributorId: request.params.distributorId,
  };
  const result = await deps.useCases.distributors.get.execute(input);
  return reply.code(200).send(result);
}


