/**
 * Handlers for Resume
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DistributorsDomainModule } from "../dependencies/distributors-ddd.dependencies.js";
import type { ResumeDistributorInput } from "@shelfline/services/distributors";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/distributors/{distributorId}/resume
 * Operation: resumeDistributor
 */
export async function resumeDistributor(
  request: FastifyRequest<{ Params: { distributorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DistributorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ResumeDistributorInput = {
    distributorId: request.params.distributorId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.resumes.get.execute(input);
  return reply.code(200).send(result);
}


