/**
 * ExecuteOpenComplaint - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenComplaint Use Case
 *
 * DDD: Application use case for get Complaint.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenComplaintInput, OpenComplaintOutput } from "../dto/complaint.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { ComplaintRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteOpenComplaint {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complaint: ComplaintRepository
  ) {}

  async execute(input: OpenComplaintInput): Promise<OpenComplaintOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmpId();

    // All field names extracted from OpenAPI spec: applicationId, distributorId, narrative
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).applicationId) {
      throw new ValidationError("applicationId is required");
    }
    const applicationId = (input as any).applicationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.complaint.openComplaint({ applicationId: applicationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${applicationId}`);
    }

    return entity as OpenComplaintOutput;
  }
}
