/**
 * Routes for Contract
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { amendDistributionContract, createDistributionContract, getDistributionContract, listDistributionContracts } from "../handlers/contract.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function contractRoutes(fastify: FastifyInstance) {
  // POST /v1/distributors/{distributorId}/contracts (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/distributors/:distributorId/contracts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { distributorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDistributorsDependenciesForRequest();
        await createDistributionContract(request, reply, deps);
      });
    }
  );


  // GET /v1/distributors/{distributorId}/contracts (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/distributors/:distributorId/contracts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { distributorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDistributorsDependenciesForRequest();
        await listDistributionContracts(request, reply, deps);
      });
    }
  );


  // PATCH /v1/distributors/{distributorId}/contracts/{contractId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/distributors/:distributorId/contracts/:contractId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { distributorId: string, contractId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDistributorsDependenciesForRequest();
        await amendDistributionContract(request, reply, deps);
      });
    }
  );


  // GET /v1/distributors/{distributorId}/contracts/{contractId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/distributors/:distributorId/contracts/:contractId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { distributorId: string, contractId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDistributorsDependenciesForRequest();
        await getDistributionContract(request, reply, deps);
      });
    }
  );


}
