/**
 * Routes for Pause
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { pauseDistributor } from "../handlers/pause.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function pauseRoutes(fastify: FastifyInstance) {
  // POST /v1/distributors/{distributorId}/pause (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/distributors/:distributorId/pause",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { distributorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDistributorsDependenciesForRequest();
        await pauseDistributor(request, reply, deps);
      });
    }
  );


}
