/**
 * ExecuteCreateDistributionContract - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDistributionContract Use Case
 *
 * DDD: Application use case for create Contract.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDistributionContractInput, CreateDistributionContractOutput } from "../dto/contract.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { ContractRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanCreate } from "../policies/can-create.policy.js";
export class ExecuteCreateDistributionContract {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contract: ContractRepository
  ) {}

  async execute(input: CreateDistributionContractInput): Promise<CreateDistributionContractOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dstId();

    // All field names extracted from OpenAPI spec: brandOwner, complaintOwner, manufacturingPrice, recommendationBiasLimit, revenueSharePct, skuId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.skuId) {
      throw new ValidationError("skuId is required");
    }
    if (!input.complaintOwner) {
      throw new ValidationError("complaintOwner is required");
    }
    if (!input.brandOwner) {
      throw new ValidationError("brandOwner is required");
    }
    if (!input.revenueSharePct) {
      throw new ValidationError("revenueSharePct is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (distributors domain)
    const entityId = this.idGenerator.dstId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.contract.createDistributionContract({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDistributionContractOutput;
  }
}
