/**
 * ExecuteRegisterDistributor - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterDistributor Use Case
 *
 * DDD: Application use case for create Distributor.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterDistributorInput, RegisterDistributorOutput } from "../dto/distributor.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { DistributorRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanCreate } from "../policies/can-create.policy.js";
export class ExecuteRegisterDistributor {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly distributor: DistributorRepository
  ) {}

  async execute(input: RegisterDistributorInput): Promise<RegisterDistributorOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dstId();

    // All field names extracted from OpenAPI spec: channelType, legalName
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.legalName) {
      throw new ValidationError("legalName is required");
    }
    if (!input.channelType) {
      throw new ValidationError("channelType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (distributors domain)
    const entityId = this.idGenerator.dstId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.distributor.registerDistributor({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterDistributorOutput;
  }
}
