/**
 * ExecuteUpsertLiquidityCap - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertLiquidityCap Use Case
 *
 * DDD: Application use case for get Cap.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertLiquidityCapInput, UpsertLiquidityCapOutput } from "../dto/cap.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { CapRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteUpsertLiquidityCap {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cap: CapRepository
  ) {}

  async execute(input: UpsertLiquidityCapInput): Promise<UpsertLiquidityCapOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.thrId();

    // All field names extracted from OpenAPI spec: maxBalance, skuId, tenureBand, warningThresholdPct
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).skuId) {
      throw new ValidationError("skuId is required");
    }
    const skuId = (input as any).skuId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.cap.upsertLiquidityCap({ skuId: skuId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${skuId}`);
    }

    return entity as UpsertLiquidityCapOutput;
  }
}
