/**
 * GetBreach handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getBreach } from "@shelfline/api-server/domains/breaches/handlers";
import type { BreachesDDDDependencies } from "@shelfline/api-server/domains/breaches";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@shelfline/tests/shared";
import { BREACHES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetBreach", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BreachesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BreachesDDDDependencies>(
      BREACHES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetBreach, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { breachId: entity.id };

    await getBreach(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetBreach.execute).toHaveBeenCalledWith(expect.objectContaining({ breachId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { breachId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetBreach, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getBreach(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
