/**
 * ExecuteListFairnessAttestations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFairnessAttestations Use Case
 *
 * DDD: Application use case for list Attestation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFairnessAttestationsInput, ListFairnessAttestationsOutput } from "../dto/attestation.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { AttestationRepository } from "../ports/index.js";

export class ExecuteListFairnessAttestations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attestation: AttestationRepository
  ) {}

  async execute(input: ListFairnessAttestationsInput): Promise<ListFairnessAttestationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.attestation.listFairnessAttestations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFairnessAttestationsOutput;
  }
}
