/**
 * ExecuteListBreaches - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBreaches Use Case
 *
 * DDD: Application use case for list Breach.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBreachesInput, ListBreachesOutput } from "../dto/breach.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { BreachRepository } from "../ports/index.js";

export class ExecuteListBreaches {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly breach: BreachRepository
  ) {}

  async execute(input: ListBreachesInput): Promise<ListBreachesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.breach.listBreaches({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBreachesOutput;
  }
}
