/**
 * ExecuteCreateFairnessAttestation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateFairnessAttestation Use Case
 *
 * DDD: Application use case for create Attestation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateFairnessAttestationInput, CreateFairnessAttestationOutput } from "../dto/attestation.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { AttestationRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanCreate } from "../policies/can-create.policy.js";
export class ExecuteCreateFairnessAttestation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attestation: AttestationRepository
  ) {}

  async execute(input: CreateFairnessAttestationInput): Promise<CreateFairnessAttestationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brcId();

    // All field names extracted from OpenAPI spec: attestedBy, channelCompareNote, leakageFindings
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.attestedBy) {
      throw new ValidationError("attestedBy is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (breaches domain)
    const entityId = this.idGenerator.brcId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.attestation.createFairnessAttestation({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateFairnessAttestationOutput;
  }
}
