/**
 * ExecuteRecordBreach - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordBreach Use Case
 *
 * DDD: Application use case for get Breach.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordBreachInput, RecordBreachOutput } from "../dto/breach.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { BreachRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteRecordBreach {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly breach: BreachRepository
  ) {}

  async execute(input: RecordBreachInput): Promise<RecordBreachOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brcId();

    // All field names extracted from OpenAPI spec: detail, distributorId, type
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).distributorId) {
      throw new ValidationError("distributorId is required");
    }
    const distributorId = (input as any).distributorId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.breach.recordBreach({ distributorId: distributorId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${distributorId}`);
    }

    return entity as RecordBreachOutput;
  }
}
