/**
 * Assign DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaints
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assign DTOs
 *
 * DDD: Application DTOs for Assign use cases.
 */

import type { AssignComplaintParams, AssignComplaintRequestInput } from "@shelfline/core/complaints/types";

export type AssignComplaintInput = AssignComplaintParams & AssignComplaintRequestInput;

export type AssignComplaintOutput = {};
