/**
 * Routes for CapitalConstraint
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSkuCapitalConstraint, upsertSkuCapitalConstraint } from "../handlers/capital-constraint.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function capitalConstraintRoutes(fastify: FastifyInstance) {
  // GET /v1/skus/{skuId}/capital-constraint (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/skus/:skuId/capital-constraint",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await getSkuCapitalConstraint(request, reply, deps);
      });
    }
  );


  // PUT /v1/skus/{skuId}/capital-constraint (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/skus/:skuId/capital-constraint",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await upsertSkuCapitalConstraint(request, reply, deps);
      });
    }
  );


}
