/**
 * Routes for RateCard
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listSkuRateCards, upsertRateCard } from "../handlers/rate-card.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function rateCardRoutes(fastify: FastifyInstance) {
  // GET /v1/skus/{skuId}/rate-cards (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/skus/:skuId/rate-cards",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await listSkuRateCards(request, reply, deps);
      });
    }
  );


  // POST /v1/skus/{skuId}/rate-cards (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/skus/:skuId/rate-cards",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await upsertRateCard(request, reply, deps);
      });
    }
  );


}
