/**
 * Routes for Retire
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { retireProductSku } from "../handlers/retire.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function retireRoutes(fastify: FastifyInstance) {
  // POST /v1/skus/{skuId}/retire (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/skus/:skuId/retire",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await retireProductSku(request, reply, deps);
      });
    }
  );


}
