/**
 * Routes for Sku
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createProductSku, getProductSku, listProductSkus, updateProductSku } from "../handlers/sku.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function skuRoutes(fastify: FastifyInstance) {
  // POST /v1/skus (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/skus",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await createProductSku(request, reply, deps);
      });
    }
  );


  // GET /v1/skus (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/skus",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await listProductSkus(request, reply, deps);
      });
    }
  );


  // GET /v1/skus/{skuId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/skus/:skuId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await getProductSku(request, reply, deps);
      });
    }
  );


  // PATCH /v1/skus/{skuId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/skus/:skuId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { skuId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSkusDependenciesForRequest();
        await updateProductSku(request, reply, deps);
      });
    }
  );


}
