/**
 * ListMargin DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListMarginSnapshotsParams } from "@shelfline/core/telemetry";

export function createListMarginRequest(overrides: Partial<ListMarginSnapshotsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
