/**
 * CapRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CapRepository Port
 *
 * DDD: Application port for caprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListLiquidityCapsInput, ListLiquidityCapsOutput, UpsertLiquidityCapInput, UpsertLiquidityCapOutput } from "../dto/cap.dto.js";
export interface CapRepository {
  listLiquidityCaps(input: ListLiquidityCapsInput): Promise<ListLiquidityCapsOutput>;
  upsertLiquidityCap(input: UpsertLiquidityCapInput): Promise<UpsertLiquidityCapOutput>;
}

export type { ListLiquidityCapsInput, ListLiquidityCapsOutput, UpsertLiquidityCapInput, UpsertLiquidityCapOutput } from "../dto/cap.dto.js";
