/**
 * ForceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: throttles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForceRepository Port
 *
 * DDD: Application port for forcerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ForceThrottleInput, ForceThrottleOutput } from "../dto/force.dto.js";
export interface ForceRepository {
  forceThrottle(input: ForceThrottleInput): Promise<ForceThrottleOutput>;
}

export type { ForceThrottleInput, ForceThrottleOutput } from "../dto/force.dto.js";
