/**
 * AttestationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttestationRepository Port
 *
 * DDD: Application port for attestationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateFairnessAttestationInput, CreateFairnessAttestationOutput, ListFairnessAttestationsInput, ListFairnessAttestationsOutput } from "../dto/attestation.dto.js";
export interface AttestationRepository {
  listFairnessAttestations(input: ListFairnessAttestationsInput): Promise<ListFairnessAttestationsOutput>;
  createFairnessAttestation(input: CreateFairnessAttestationInput): Promise<CreateFairnessAttestationOutput>;
}

export type { CreateFairnessAttestationInput, CreateFairnessAttestationOutput, ListFairnessAttestationsInput, ListFairnessAttestationsOutput } from "../dto/attestation.dto.js";
