/**
 * RemediateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediateRepository Port
 *
 * DDD: Application port for remediaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RemediateBreachInput, RemediateBreachOutput } from "../dto/remediate.dto.js";
export interface RemediateRepository {
  remediateBreach(input: RemediateBreachInput): Promise<RemediateBreachOutput>;
}

export type { RemediateBreachInput, RemediateBreachOutput } from "../dto/remediate.dto.js";
