/**
 * ExecuteCreateProductSku - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateProductSku Use Case
 *
 * DDD: Application use case for create Sku.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateProductSkuInput, CreateProductSkuOutput } from "../dto/sku.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { SkuRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanCreate } from "../policies/can-create.policy.js";
export class ExecuteCreateProductSku {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly sku: SkuRepository
  ) {}

  async execute(input: CreateProductSkuInput): Promise<CreateProductSkuOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.skuId();

    // All field names extracted from OpenAPI spec: adjudicationMode, crossSubsidyDeclared, crossSubsidyNote, manufacturingPrice, name, priceFloor, productFamily, role
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.role) {
      throw new ValidationError("role is required");
    }
    if (!input.productFamily) {
      throw new ValidationError("productFamily is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (skus domain)
    const entityId = this.idGenerator.skuId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.sku.createProductSku({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateProductSkuOutput;
  }
}
