/**
 * ExecuteUpsertRateCard - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertRateCard Use Case
 *
 * DDD: Application use case for get RateCard.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertRateCardInput, UpsertRateCardOutput } from "../dto/rate-card.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { RateCardRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteUpsertRateCard {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rateCard: RateCardRepository
  ) {}

  async execute(input: UpsertRateCardInput): Promise<UpsertRateCardOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.skuId();

    // All field names extracted from OpenAPI spec: approvedMax, approvedMin, effectiveFrom, rate
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).skuId) {
      throw new ValidationError("skuId is required");
    }
    const skuId = (input as any).skuId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.rateCard.upsertRateCard({ skuId: skuId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${skuId}`);
    }

    return entity as UpsertRateCardOutput;
  }
}
