/**
 * ExecuteUpdateProductSku - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateProductSku Use Case
 *
 * DDD: Application use case for update Sku.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateProductSkuInput, UpdateProductSkuOutput } from "../dto/sku.dto.js";
import type { ExecutionContextService, IdGeneratorService } from "@shelfline/services/_shared/index.js";
import type { SkuRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanUpdate } from "../policies/can-update.policy.js";
export class ExecuteUpdateProductSku {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly sku: SkuRepository
  ) {}

  async execute(input: UpdateProductSkuInput): Promise<UpdateProductSkuOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.skuId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).skuId) {
      throw new ValidationError("skuId is required");
    }
    const skuId = (input as any).skuId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.sku.updateProductSku({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateProductSkuOutput;
  }
}
