/**
 * CreatePublish DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: skus
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { PublishProductSkuParams } from "@shelfline/core/skus";

export function createCreatePublishRequest(overrides: Partial<PublishProductSkuParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
