/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: originations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./decision-repository.ddb.js";
export * from "./exposure-signal-repository.ddb.js";
export * from "./origination-repository.ddb.js";
export * from "./decision-repository.adapter.js";
export * from "./exposure-signal-repository.adapter.js";
export * from "./origination-repository.adapter.js";
