/**
 * Distributors DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: distributors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Distributors Domain Module - Composition root
 *
 * DDD: Composition root for distributors domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ActivateRepositoryAdapter,
  ContractRepositoryAdapter,
  DistributorRepositoryAdapter,
  PauseRepositoryAdapter,
  ResumeRepositoryAdapter,
} from "@shelfline/adapters/distributors";
import { getIdGeneratorService } from "@shelfline/adapters";
import type { AdapterDynamoDBClient } from "@shelfline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAmendDistributionContract,
  ExecuteCreateDistributionContract,
  ExecuteGetDistributionContract,
  ExecuteGetDistributor,
  ExecuteListDistributionContracts,
  ExecuteListDistributors,
  ExecuteRegisterDistributor,
} from "@shelfline/services/distributors/usecases";
// Ports (interfaces)
import type {
  ActivateRepository,
  ContractRepository,
  DistributorRepository,
  PauseRepository,
  ResumeRepository,
} from "@shelfline/services/distributors/ports";

export interface DistributorsDomainModule {
  repos: {
    activates: ActivateRepository;
    contracts: ContractRepository;
    distributors: DistributorRepository;
    pauses: PauseRepository;
    resumes: ResumeRepository;
  };
  useCases: {
    contracts: {
      create: ExecuteCreateDistributionContract;
      get: ExecuteAmendDistributionContract;
      list: ExecuteListDistributionContracts;
    };
    distributors: {
      create: ExecuteRegisterDistributor;
      get: ExecuteGetDistributor;
      list: ExecuteListDistributors;
    };
  };
}

export function buildDistributorsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DistributorsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      activates?: ActivateRepository;
      contracts?: ContractRepository;
      distributors?: DistributorRepository;
      pauses?: PauseRepository;
      resumes?: ResumeRepository;
    } = {};

    obj.activates = new ActivateRepositoryAdapter(dynamoClient);
    obj.contracts = new ContractRepositoryAdapter(dynamoClient);
    obj.distributors = new DistributorRepositoryAdapter(dynamoClient);
    obj.pauses = new PauseRepositoryAdapter(dynamoClient);
    obj.resumes = new ResumeRepositoryAdapter(dynamoClient);
    return {
      activates: obj.activates!,
      contracts: obj.contracts!,
      distributors: obj.distributors!,
      pauses: obj.pauses!,
      resumes: obj.resumes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    contracts: {
      create: new ExecuteCreateDistributionContract(executionContext, idGenerator, repos.contracts),
      get: new ExecuteAmendDistributionContract(executionContext, idGenerator, repos.contracts),
      list: new ExecuteListDistributionContracts(executionContext, idGenerator, repos.contracts),
    },
    distributors: {
      create: new ExecuteRegisterDistributor(executionContext, idGenerator, repos.distributors),
      get: new ExecuteGetDistributor(executionContext, idGenerator, repos.distributors),
      list: new ExecuteListDistributors(executionContext, idGenerator, repos.distributors),
    },
  };
  return { repos, useCases: useCases as DistributorsDomainModule["useCases"] };
}
