/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breaches
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { attestationRoutes } from "./attestation.routes.js";
export { breachRoutes } from "./breach.routes.js";
export { remediateRoutes } from "./remediate.routes.js";
